"use client";

import { useState } from "react";

const money = new Intl.NumberFormat("en-GH", { style: "currency", currency: "GHS" });
const dateTime = (value) => value ? new Date(value).toLocaleString("en-GH", { dateStyle: "medium", timeStyle: "short" }) : "—";
const statuses = ["pending", "confirmed", "paid", "processing", "ready", "completed", "cancelled"];

export default function PosOrders({ role, orders, visibleOrders, orderQuery, setOrderQuery, orderStatus, setOrderStatus, busy, error, openOrderAtTill, updateOrder, newOrderNotice, clearNewOrderNotice }) {
  const [selected, setSelected] = useState(null);
  const openCount = orders.filter((order) => !["completed", "cancelled"].includes(order.status)).length;
  return <main className="pos-orders"><div className="pos-title"><div><p className="eyebrow">All channels</p><h1>Orders</h1><p>{openCount} open orders awaiting payment or fulfilment.</p></div>{["owner", "admin", "supervisor"].includes(role) && <a className="button secondary" href="/admin">Admin Portal</a>}</div>
    {newOrderNotice && <div className="notice success-notice pos-order-notice" role="status"><span>{newOrderNotice}</span><button type="button" onClick={clearNewOrderNotice} aria-label="Dismiss new order notice">×</button></div>}
    <div className="table-tools"><input aria-label="Search orders" placeholder="Search client, phone, reference or time" value={orderQuery} onChange={(event) => setOrderQuery(event.target.value)} /><select aria-label="Filter order status" value={orderStatus} onChange={(event) => setOrderStatus(event.target.value)}><option value="all">All orders</option><option value="pending-payment">Pending payment</option><option value="pending">Pending</option><option value="processing">Processing</option><option value="ready">Ready</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select><span>{visibleOrders.length} orders</span></div>
    {error && <p className="notice error-notice" role="alert">{error}</p>}
    {visibleOrders.length ? <div className="summary-grid">{visibleOrders.map((order) => <button type="button" className="summary-card" key={order.orderId} onClick={() => setSelected(order)} aria-label={`Open order for ${order.customer || "Guest"}`}><strong>{order.customer || "Guest"}</strong><span>{order.phone || "No phone"}</span><div className="summary-statuses"><span className={order.paymentStatus === "paid" ? "badge success" : "badge neutral"}>{order.paymentStatus || "unpaid"}</span><span className={order.status === "completed" ? "badge success" : order.status === "cancelled" ? "badge danger" : "badge warning"}>{order.status || "pending"}</span></div></button>)}</div> : <div className="empty-state">No orders match these filters.</div>}
    {selected && <div className="modal-backdrop" role="presentation" onMouseDown={() => setSelected(null)}><div className="modal pos-order-detail" role="dialog" aria-modal="true" aria-label={`Order ${selected.orderId}`} onMouseDown={(event) => event.stopPropagation()}><div className="drawer-title"><div><p className="eyebrow">Order details</p><h2>{selected.orderId}</h2></div><button className="icon-button" aria-label="Close order details" onClick={() => setSelected(null)}>×</button></div><div className="detail-grid"><div><span>Customer</span><b>{selected.customer || "Guest"}</b></div><div><span>Phone</span><b>{selected.phone || "—"}</b></div><div><span>Created</span><b>{dateTime(selected.createdAt)}</b></div><div><span>Channel</span><b>{selected.channel || "website"}</b></div><div><span>Fulfilment</span><b>{selected.deliveryMethod || "Pickup"}</b></div><div><span>Payment</span><b>{selected.paymentStatus || "pending"}</b></div><div><span>Status</span><b>{selected.status || "pending"}</b></div><div><span>Destination</span><b>{selected.deliveryAddress || selected.landmark || "—"}</b></div>{selected.pickupCode && <div><span>Pickup code</span><b>{selected.pickupCode}</b></div>}</div>{selected.notes && <p>Notes: {selected.notes}</p>}<div className="pos-order-detail-lines">{(selected.items || []).map((item, index) => <div key={`${item.productId}-${index}`}><span>{item.quantity} × {item.name}<small>{[item.colour, item.size, item.sku || item.productId].filter(Boolean).join(" · ")}</small></span><b>{money.format(item.lineTotal || Number(item.price || 0) * Number(item.quantity || 0))}</b></div>)}</div><div className="order-total"><span>Total</span><strong>{money.format(selected.total || 0)}</strong></div><label className="detail-status-control">Update fulfilment status<select aria-label={`Update ${selected.orderId}`} disabled={busy} value={selected.status} onChange={async (event) => { await updateOrder(selected.orderId, event.target.value); setSelected(null); }}>{statuses.map((status) => <option key={status}>{status}</option>)}</select></label><button className="button primary full" disabled={busy || ["completed", "cancelled"].includes(selected.status)} onClick={() => { openOrderAtTill(selected); setSelected(null); }}>Open at till</button></div></div>}
  </main>;
}

