"use client";

import { useState } from "react";

const money = new Intl.NumberFormat("en-GH", { style: "currency", currency: "GHS" });
const dateTime = (value) => value ? new Date(value).toLocaleString("en-GH", { dateStyle: "medium", timeStyle: "short" }) : "—";
const statuses = ["pending", "confirmed", "paid", "processing", "ready", "completed", "cancelled"];

export default function PosOrders({ role, orders, visibleOrders, orderQuery, setOrderQuery, orderStatus, setOrderStatus, busy, error, openOrderAtTill, updateOrder, newOrderNotice, clearNewOrderNotice }) {
  const [selected, setSelected] = useState(null);
  const openCount = orders.filter((order) => !["completed", "cancelled"].includes(order.status)).length;
  return <main className="pos-orders"><div className="pos-title"><div><p className="eyebrow">All channels</p><h1>Orders</h1><p>{openCount} open orders awaiting payment or fulfilment.</p></div>{["owner", "admin", "supervisor"].includes(role) && <a className="button secondary" href="/admin">Admin Portal</a>}</div>
    {newOrderNotice && <div className="notice success-notice pos-order-notice" role="status"><span>{newOrderNotice}</span><button type="button" onClick={clearNewOrderNotice} aria-label="Dismiss new order notice">×</button></div>}
    <div className="table-tools"><input aria-label="Search orders" placeholder="Search client, phone, reference or time" value={orderQuery} onChange={(event) => setOrderQuery(event.target.value)} /><select aria-label="Filter order status" value={orderStatus} onChange={(event) => setOrderStatus(event.target.value)}><option value="all">All orders</option><option value="pending-payment">Pending payment</option><option value="pending">Pending</option><option value="processing">Processing</option><option value="ready">Ready</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select><span>{visibleOrders.length} orders</span></div>
    {error && <p className="notice error-notice" role="alert">{error}</p>}
    <div className="data-table-wrap"><table className="data-table pos-order-table"><thead><tr><th>Order</th><th>Customer</th><th>Fulfilment</th><th>Items</th><th>Total</th><th>Payment</th><th>Status</th><th>Action</th><th>Update</th></tr></thead><tbody>{visibleOrders.length ? visibleOrders.map((order) => <tr key={order.orderId}><td><b>{order.orderId}</b><span>{dateTime(order.createdAt)}</span></td><td><b>{order.customer || "Guest"}</b><span>{order.phone || "—"}</span></td><td>{order.deliveryMethod || "—"}<span>{order.channel || "website"}</span></td><td>{(order.items || []).reduce((count, item) => count + Number(item.quantity || 0), 0)}</td><td className="num">{money.format(order.total || 0)}</td><td><span className={order.paymentStatus === "paid" ? "badge success" : "badge neutral"}>{order.paymentStatus || "pending"}</span></td><td><span className={order.status === "completed" ? "badge success" : order.status === "cancelled" ? "badge danger" : "badge warning"}>{order.status || "pending"}</span></td><td><div className="pos-order-actions"><button className="table-action" type="button" onClick={() => setSelected(order)}>View</button><button className="table-action" type="button" disabled={busy || ["completed", "cancelled"].includes(order.status)} onClick={() => openOrderAtTill(order)}>Open at till</button></div></td><td><select aria-label={`Update ${order.orderId}`} disabled={busy} value={order.status} onChange={(event) => updateOrder(order.orderId, event.target.value)}>{statuses.map((status) => <option key={status}>{status}</option>)}</select></td></tr>) : <tr><td colSpan="9" className="empty-cell">No orders match these filters.</td></tr>}</tbody></table></div>
    {selected && <div className="modal-backdrop" role="presentation" onMouseDown={() => setSelected(null)}><div className="modal pos-order-detail" role="dialog" aria-modal="true" aria-label={`Order ${selected.orderId}`} onMouseDown={(event) => event.stopPropagation()}><div className="drawer-title"><div><p className="eyebrow">Order details</p><h2>{selected.orderId}</h2></div><button className="icon-button" aria-label="Close order details" onClick={() => setSelected(null)}>×</button></div><p>{dateTime(selected.createdAt)} · {selected.customer || "Guest"} · {selected.phone || "No phone"}</p><p>{selected.deliveryMethod || "Pickup"} · {selected.paymentStatus || "pending payment"}</p>{selected.deliveryAddress && <p>Destination: {selected.deliveryAddress}</p>}{selected.notes && <p>Notes: {selected.notes}</p>}<div className="pos-order-detail-lines">{(selected.items || []).map((item, index) => <div key={`${item.productId}-${index}`}><span>{item.quantity} × {item.name}<small>{[item.colour, item.size, item.sku || item.productId].filter(Boolean).join(" · ")}</small></span><b>{money.format(item.lineTotal || Number(item.price || 0) * Number(item.quantity || 0))}</b></div>)}</div><div className="order-total"><span>Total</span><strong>{money.format(selected.total || 0)}</strong></div><button className="button primary full" disabled={busy || ["completed", "cancelled"].includes(selected.status)} onClick={() => { openOrderAtTill(selected); setSelected(null); }}>Open at till</button></div></div>}
  </main>;
}

