"use client";

import { useMemo, useRef, useState } from "react";
import useBarcodeCamera from "@/components/useBarcodeCamera";
import BarcodeScannerPanel from "@/components/BarcodeScannerPanel";
import ScannerPrompt from "@/components/ScannerPrompt";
import { cardImageSource } from "@/lib/productImages.mjs";
import PosQuantityStepper from "@/components/PosQuantityStepper";
import ReceiptPanel from "@/components/ReceiptPanel";
import { activeRule } from "@/lib/discount.mjs";
import { appliedOfferBadge, appliedOfferLabel } from "@/lib/quantityOffer.mjs";
import { isPromotion, promotionPrice } from "@/lib/catalogueBrowse.mjs";
import { variantDetail } from "@/lib/variantDisplay.mjs";

const money = new Intl.NumberFormat("en-GH", { style: "currency", currency: "GHS" });

export default function PosTill({ products = [], scanPrompt, scanFeedback, dismissScanPrompt, confirmScanIncrease, onSelectScannedProduct, shift, role, query, setQuery, barcode, setBarcode, barcodeInput, scanBarcode, onScannedCode, scanMatches, setScanMatches, category, setCategory, categories, stockFilter, setStockFilter, visible, add, cart, setCart, cartNotice, setCartNotice, change, setQuantity, pricing, discountRules = [], orderReference, setOrderReference, orderChannel, setOrderChannel, customerName, setCustomerName, customerPhone, setCustomerPhone, paymentMethod, setPaymentMethod, amountPaid, setAmountPaid, transactionVerified, setTransactionVerified, changeDue, paymentReady, referenceReady, online, busy, setConfirmSale }) {
  const { subtotal, discount, total } = pricing;
  const [cartOpen, setCartOpen] = useState(false);
  const [checkoutStep, setCheckoutStep] = useState(false);
  const [scannerMessage, setScannerMessage] = useState("");
  const [showSuggestions, setShowSuggestions] = useState(false);
  const [previewOpen, setPreviewOpen] = useState(false);
  const [scannerSearchOpen, setScannerSearchOpen] = useState(false);
  const [scannerSearch, setScannerSearch] = useState("");
  const searchInput = useRef(null);
  const { cameraOpen, videoRef, openCamera, closeCamera } = useBarcodeCamera(onScannedCode, setScannerMessage, { continuous: true, keepOpenOnError: true, paused: Boolean(scanPrompt) || scanMatches.length > 0 || scannerSearchOpen });
  function openScanner() { setScannerSearchOpen(false); setScannerSearch(""); setScannerMessage(""); openCamera(); }
  function viewBasket() {
    closeCamera(); setScanMatches([]); setCartOpen(true); setCheckoutStep(true);
    requestAnimationFrame(() => { const basket = document.getElementById("pos-current-basket"); basket?.scrollIntoView({ behavior: "instant", block: "nearest" }); basket?.focus({ preventScroll: true }); });
  }
  const scannerProducts = scannerSearch.trim() ? products.filter((product) => `${product.name} ${product.sku || product.id}`.toLowerCase().includes(scannerSearch.trim().toLowerCase())).slice(0, 15) : [];

  const uniqueMatch = useMemo(() => visible.filter((product) => product.stock > 0), [visible]);
  const selectUnique = (event) => {
    if (event.key === "Enter" && uniqueMatch.length === 1) { event.preventDefault(); add(uniqueMatch[0]); setQuery(""); }
  };
  const suggestions = query.trim() ? visible.slice(0, 6) : [];
  const basketRows = cart.map((item) => ({ item, priced: pricing.lines.find((line) => line.id === item.id) }));
  const hasQuantityDiscount = discountRules.some((rule) => activeRule(rule) && rule.scopeType === "GLOBAL" && rule.discountType === "PERCENT" && Number(rule.value) === 5 && Number(rule.minQty) === 3);
  const clearBasket = () => { setCart([]); setCheckoutStep(false); setOrderReference(""); setOrderChannel("walk-in"); setCustomerName(""); setCustomerPhone(""); setAmountPaid(""); setTransactionVerified(false); };
  const previewSale = { createdAt: new Date().toISOString(), staffName: shift.staffName || "Staff", salesChannel: orderChannel, paymentMethod, customerName, customerPhone, orderReference, subtotal, discount, total, amountPaid: Number(amountPaid || 0), change: changeDue, items: basketRows.map(({ item, priced }) => ({ ...item, unitPrice: item.price, lineTotal: priced?.lineTotal ?? item.price * item.quantity })) };
  return <main className="pos-main">
    <section className="pos-catalogue">
      <div className="pos-title"><div><p className="eyebrow">Point of sale · {shift.shiftId}</p><h1>New sale</h1></div>{["owner", "admin"].includes(role) && <a className="button secondary" href="/admin">Admin Portal</a>}</div>
      <div className="pos-search-row"><div className="pos-search-wrap"><label htmlFor="pos-product-search">Search product name or SKU</label><input id="pos-product-search" className="pos-search" autoFocus placeholder="Start typing to filter products" value={query} onFocus={() => setShowSuggestions(true)} onBlur={() => setTimeout(() => setShowSuggestions(false), 150)} onChange={(event) => { setQuery(event.target.value); setShowSuggestions(true); }} onKeyDown={selectUnique} />{showSuggestions && suggestions.length > 0 && <div className="pos-suggestions" role="listbox" aria-label="Matching products">{suggestions.map((product) => <button type="button" role="option" aria-selected="false" key={product.id} disabled={product.stock <= 0} onMouseDown={(event) => event.preventDefault()} onClick={() => { add(product); setQuery(""); setShowSuggestions(false); }}>{cardImageSource(product).url ? <img src={cardImageSource(product).url} alt="" /> : <span className="product-monogram">{product.name.slice(0, 2).toUpperCase()}</span>}<span><b>{product.name}</b><small>{product.sku || product.id} · {money.format(product.price)}</small></span></button>)}</div>}</div><form className="pos-scan-actions" onSubmit={scanBarcode}><input ref={barcodeInput} className="pos-scanner-input" aria-label="Scanned barcode, QR code or SKU" autoComplete="off" value={barcode} onChange={(event) => setBarcode(event.target.value)} /><button type="button" className="button secondary" onClick={() => { if (window.matchMedia("(pointer: coarse)").matches) openScanner(); else { barcodeInput.current?.focus(); setScannerMessage("Scanner ready. Scan a barcode or type a code, then press Enter."); } }}>Scan Code</button><button type="button" className="button secondary" onClick={openScanner}>Use camera</button></form></div>
      {scannerMessage && <p className="notice" role="status">{scannerMessage}</p>}
      {!cameraOpen && scanMatches.length > 0 && <div className="pos-scan-matches" role="dialog" aria-label="Choose scanned product"><div className="drawer-title"><h2>Choose a product</h2><button type="button" className="icon-button" onClick={() => setScanMatches([])} aria-label="Close choices">×</button></div>{scanMatches.map((product) => <button type="button" key={product.id} disabled={product.stock <= 0} onClick={() => { onSelectScannedProduct(product); }}>{product.name} · {product.sku || product.id} {product.stock <= 0 ? "· Out of stock" : ""}</button>)}</div>}
      {cameraOpen && <BarcodeScannerPanel title="Scan products into basket" videoRef={videoRef} onClose={closeCamera} actions={<><button type="button" className="button secondary" onClick={() => { setScannerSearchOpen((current) => !current); requestAnimationFrame(() => searchInput.current?.focus()); }}>Search</button><button type="button" className="button primary" disabled={!cart.length} onClick={viewBasket}>View basket ({cart.reduce((sum, item) => sum + item.quantity, 0)})</button></>}>
        {scannerMessage && <p className="notice" role="status">{scannerMessage}</p>}{scanFeedback && <p className="notice" role="status">{scanFeedback}</p>}{cartNotice && <p className="notice error-notice" role="alert">{cartNotice}</p>}
        <div className="scanner-code-entry"><label>Barcode, QR code or SKU<input value={barcode} autoComplete="off" placeholder="Scan with a connected reader or type a code" onChange={(event) => setBarcode(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") { event.preventDefault(); if (event.currentTarget.value.trim()) onScannedCode(event.currentTarget.value); } }} /></label><button type="button" className="button secondary" disabled={!barcode.trim()} onClick={() => onScannedCode(barcode)}>Add scanned item</button></div>
        {scannerSearchOpen && <section className="scanner-manual-search"><label>Search product name or SKU<input ref={searchInput} value={scannerSearch} placeholder="Find products without a barcode" onChange={(event) => setScannerSearch(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && scannerProducts.length === 1) { event.preventDefault(); onSelectScannedProduct(scannerProducts[0]); } }} /></label><div className="scanner-search-results">{scannerProducts.map((product) => <button type="button" key={product.id} disabled={product.stock <= 0} onClick={() => onSelectScannedProduct(product)}><strong>{product.name}</strong><small>{product.sku || product.id} · {variantDetail(product)} · {money.format(product.price)} · {product.stock > 0 ? `${product.stock} in stock` : "Out of stock"}</small></button>)}{scannerSearch.trim() && !scannerProducts.length && <p>No matching products.</p>}</div><button type="button" className="text-button" onClick={() => setScannerSearchOpen(false)}>Continue camera scanning</button></section>}
        {scanMatches.length > 0 && <section className="scanner-search-results"><h3>Choose scanned product</h3>{scanMatches.map((product) => <button type="button" key={product.id} disabled={product.stock <= 0} onClick={() => onSelectScannedProduct(product)}>{product.name} · {product.sku || product.id}</button>)}<button type="button" onClick={() => setScanMatches([])}>Cancel selection</button></section>}
        <h3>Current basket · {cart.reduce((sum, item) => sum + item.quantity, 0)} items</h3>
        <div className="scanner-basket-list">{cart.length ? basketRows.map(({ item, priced }) => <article key={item.id}><div><strong>{item.name}</strong><small>{item.sku || item.id}{variantDetail(item) && ` · ${variantDetail(item)}`}</small><small>{money.format(priced?.lineTotal ?? item.price * item.quantity)}</small></div><PosQuantityStepper item={item} onChange={setQuantity} /><button type="button" className="text-button" aria-label={`Remove ${item.name} from scanner basket`} onClick={() => setCart((current) => current.filter((line) => line.id !== item.id))}>Remove</button></article>) : <p>Your cart is empty. Scan a code or use Search to add products.</p>}</div>
      </BarcodeScannerPanel>}
      {scanPrompt && <ScannerPrompt title={scanPrompt.type === "increase" ? "Increase product quantity?" : "Scan notice"} message={scanPrompt.type === "increase" ? `${scanPrompt.product.name} is already in the basket. Quantity in basket: ${cart.find((item) => item.id === scanPrompt.product.id)?.quantity ?? scanPrompt.quantity}. Are you increasing product quantity by one?` : scanPrompt.message} onOk={dismissScanPrompt}>{scanPrompt.type === "increase" ? <><button type="button" autoFocus className="button secondary" onClick={dismissScanPrompt}>No</button><button type="button" className="button primary" onClick={confirmScanIncrease}>Yes</button></> : null}</ScannerPrompt>}

      <section className="pos-basket-table" aria-label="Current basket">
        <div className="drawer-title"><div><p className="eyebrow">Current basket</p><h2>{cart.reduce((sum, item) => sum + item.quantity, 0)} items · {money.format(total)}</h2></div><button type="button" className="text-button" onClick={clearBasket} disabled={!cart.length}>Clear basket</button></div>
        {hasQuantityDiscount && <div className="pos-basket-rules"><strong>Buy 3 or more of the same product to get 5% off that product.</strong></div>}
        <div className="pos-basket-scroll"><table><thead><tr><th>ITEM</th><th>QTY</th><th>UNIT PRICE</th><th>SUBTOTAL</th></tr></thead><tbody>{basketRows.map(({ item, priced }) => <tr key={item.id}><td><div className="pos-basket-item"><span><b>{item.name}</b><small>{item.sku || item.id}</small></span><button type="button" className="pos-remove-line" aria-label={`Remove ${item.name} from basket`} onClick={() => setCart((current) => current.filter((line) => line.id !== item.id))}>×</button></div></td><td><PosQuantityStepper item={item} onChange={setQuantity} />{appliedOfferLabel(priced) && <small className="pos-line-discount">{appliedOfferLabel(priced)}</small>}</td><td>{money.format(item.price)}</td><td><span className="pos-line-total">{appliedOfferBadge(priced) && <span className="pos-line-discount">{appliedOfferBadge(priced)}</span>}<strong>{money.format(priced?.lineTotal || 0)}</strong></span></td></tr>)}</tbody></table>{!cart.length && <p className="pos-basket-empty">Add a product to start this sale.</p>}</div>
      </section>
      <div className="pos-filter-row"><label>Category<select value={category} onChange={(event) => setCategory(event.target.value)}>{categories.map((item) => <option key={item}>{item}</option>)}</select></label><label>Catalogue<select value={stockFilter} onChange={(event) => setStockFilter(event.target.value)}><option value="all">All products</option><option value="high">High demand</option><option value="low">Low stock</option><option value="out">Out of stock</option></select></label><span>{visible.length} matching products</span></div>
      <div className="pos-grid">{visible.map((product) => {
        const out = product.stock <= 0;
        const low = !out && product.stock < Number(product.lowStockLevel ?? 8);
        return <button key={product.id} className="pos-product" onClick={() => add(product)} disabled={out}>{isPromotion(product, discountRules) && <span className="promo-ribbon">Promo</span>}<span className="product-monogram">{product.name.slice(0, 2).toUpperCase()}</span><b>{product.name}</b><small>{product.sku || product.id}{[product.colour, product.size].filter(Boolean).length ? ` · ${variantDetail(product)}` : ""}</small><div><strong>{promotionPrice(product, discountRules) != null ? <><del>{money.format(product.price)}</del> {money.format(promotionPrice(product, discountRules))}</> : money.format(product.price)}</strong><span className={out ? "out" : low ? "low" : "healthy"}>{out ? "Out of stock" : low ? `Low stock · ${product.stock} left` : `${product.stock} in stock`}</span></div></button>;
      })}</div>
    </section>
    <aside id="pos-current-basket" tabIndex={-1} className={`till-cart ${cartOpen ? "open" : ""} ${checkoutStep ? "checkout-step" : ""}`}><div className="drawer-title"><div><p className="eyebrow">Receipt preview</p><h2>{cart.reduce((sum, item) => sum + item.quantity, 0)} items · {money.format(total)}</h2></div><button type="button" className="pos-cart-toggle" aria-expanded={cartOpen} onClick={() => { setCartOpen((open) => !open); setCheckoutStep(false); }}>{cartOpen ? "Close basket" : "View basket"}</button><button type="button" className="text-button pos-mobile-clear" onClick={clearBasket}>Clear</button></div>
      <div className="pos-live-receipt"><div className="pos-live-receipt-paper"><img src="/brand/pam-lockup-white.svg" alt="PAM Essentials & More" /><p>Receipt preview · Final receipt number after sale</p><div className="pos-live-receipt-lines"><div className="pos-live-receipt-head"><b>ITEM</b><b>QTY</b><b>PRICE</b><b>TOTAL</b></div>{basketRows.map(({ item, priced }) => <div key={item.id}><span>{item.name}{[item.colour, item.size].filter(Boolean).length > 0 && <small>{variantDetail(item)}</small>}</span><span>{item.quantity}</span><span>{money.format(item.price)}</span><b>{money.format(priced?.lineTotal || 0)}</b></div>)}</div><div className="pos-live-receipt-total"><span>Total</span><b>{money.format(total)}</b></div></div><button type="button" className="button secondary full" onClick={() => setPreviewOpen(true)} disabled={!cart.length}>Print preview</button></div>
      <div className="till-lines">{hasQuantityDiscount && <div className="pos-basket-rules"><strong>Buy 3 or more of the same product to get 5% off that product.</strong></div>}{cart.length ? basketRows.map(({ item, priced }) => <div className="till-line" key={item.id}><button type="button" className="pos-remove-line" aria-label={`Remove ${item.name} from basket`} onClick={() => setCart((current) => current.filter((line) => line.id !== item.id))}>×</button><div className="till-line-info"><b>{item.name}</b><small>{item.sku || item.id} · {variantDetail(item)} · {money.format(item.price)} each</small></div><div className="till-line-bottom"><div><PosQuantityStepper item={item} onChange={setQuantity} />{appliedOfferLabel(priced) && <small className="pos-line-discount">{appliedOfferLabel(priced)}</small>}</div><span className="pos-line-total">{appliedOfferBadge(priced) && <span className="pos-line-discount">{appliedOfferBadge(priced)}</span>}<strong>{money.format(priced?.lineTotal || 0)}</strong></span></div></div>) : <div className="empty-state"><span className="status-icon">+</span><h3>Your cart is empty</h3><p>Select products to begin a sale.</p></div>}</div>
      <div className="till-basket-actions"><button type="button" className="button primary full" disabled={!cart.length} onClick={() => setCheckoutStep(true)}>Continue to checkout · {money.format(total)}</button></div>
      <div className="till-checkout"><button type="button" className="pos-basket-back" onClick={() => setCheckoutStep(false)}>← Review basket</button>{cartNotice && <div className="notice error-notice pos-cart-notice" role="alert"><span>{cartNotice}</span><button onClick={() => setCartNotice("")}>I reviewed the cart</button></div>}<label>Sales channel<select value={orderChannel} onChange={(event) => { setOrderChannel(event.target.value); setOrderReference(""); setCustomerName(""); setCustomerPhone(""); }}><option value="walk-in">Walk-in Sale</option><option value="website">Website Order</option><option value="whatsapp">WhatsApp Order</option><option value="phone">Phone Order</option></select></label>{orderChannel === "whatsapp" && <div className="pos-whatsapp-fields"><label>Customer order or reference<input placeholder="WhatsApp order reference" value={orderReference} onChange={(event) => setOrderReference(event.target.value)} /></label><div className="pos-customer-fields"><label>Customer name<input placeholder="Customer name" value={customerName} onChange={(event) => setCustomerName(event.target.value)} /></label><label>Phone<input type="tel" placeholder="Customer phone" value={customerPhone} onChange={(event) => setCustomerPhone(event.target.value)} /></label></div></div>}{orderChannel === "website" && <p className="linked-order-reference">{orderReference ? `Website order ${orderReference}` : "Open a website order from the Orders tab to link its reference."}</p>}
        <div className="till-summary"><div><span>Subtotal</span><strong>{money.format(subtotal)}</strong></div><div><span>Discount</span><strong>−{money.format(discount)}</strong></div><div className="grand-total"><span>Total</span><strong>{money.format(total)}</strong></div><label className="pos-payment-select">Payment type<select value={paymentMethod} onChange={(event) => { setPaymentMethod(event.target.value); setTransactionVerified(false); }}><option value="cash">Cash</option><option value="mobile-money">Mobile Money</option><option value="card">Card</option><option value="bank-transfer">Bank transfer</option></select></label><label className="amount-paid">Amount paid<input type="number" min="0" step="0.01" placeholder="Enter amount" value={amountPaid} onChange={(event) => setAmountPaid(event.target.value)} /></label>{paymentMethod !== "cash" && <label className="pos-verify"><input type="checkbox" checked={transactionVerified} onChange={(event) => setTransactionVerified(event.target.checked)} /> Transaction verified with provider</label>}{changeDue > 0 && <div className="change-due"><span>Change due</span><strong>{money.format(changeDue)}</strong></div>}<button className="button accent full" onClick={() => setConfirmSale(true)} disabled={!cart.length || !paymentReady || !referenceReady || Boolean(cartNotice) || busy}>Complete Sale</button>{!online && <p className="pos-checkout-warning">Offline sale is final at this till. Its receipt will show a pending server-sync notice; keep this device until it syncs.</p>}</div>
      </div>
    </aside>
    {previewOpen && <ReceiptPanel sale={previewSale} preview onClose={() => setPreviewOpen(false)} />}
  </main>;
}

