"use client";

import { useMemo, useState } from "react";

const money = new Intl.NumberFormat("en-GH", { style: "currency", currency: "GHS" });

export default function PosTill({ shift, role, query, setQuery, barcode, setBarcode, barcodeInput, scanBarcode, category, setCategory, categories, stockFilter, setStockFilter, visible, add, cart, setCart, cartNotice, setCartNotice, change, pricing, orderReference, setOrderReference, orderChannel, setOrderChannel, customerName, setCustomerName, customerPhone, setCustomerPhone, paymentMethod, setPaymentMethod, amountPaid, setAmountPaid, transactionVerified, setTransactionVerified, changeDue, paymentReady, referenceReady, online, busy, setConfirmSale }) {
  const { subtotal, discount, total } = pricing;
  const [cartOpen, setCartOpen] = useState(false);
  const uniqueMatch = useMemo(() => visible.filter((product) => product.stock > 0), [visible]);
  const selectUnique = (event) => {
    if (event.key === "Enter" && uniqueMatch.length === 1) { event.preventDefault(); add(uniqueMatch[0]); setQuery(""); }
  };
  return <main className="pos-main">
    <section className="pos-catalogue">
      <div className="pos-title"><div><p className="eyebrow">Point of sale · {shift.shiftId}</p><h1>New sale</h1></div>{["owner", "admin"].includes(role) && <a className="button secondary" href="/admin">Admin Portal</a>}</div>
      <div className="pos-search-row"><label>Search product name or SKU<input className="pos-search" autoFocus placeholder="Start typing to filter products" value={query} onChange={(event) => setQuery(event.target.value)} onKeyDown={selectUnique} /></label><form onSubmit={scanBarcode}><label>Scan barcode<input ref={barcodeInput} className="pos-barcode" inputMode="none" autoComplete="off" placeholder="Scan code, then Enter" value={barcode} onChange={(event) => setBarcode(event.target.value)} /></label><button type="submit" className="button secondary">Add scanned item</button></form></div>
      <div className="pos-filter-row"><label>Category<select value={category} onChange={(event) => setCategory(event.target.value)}>{categories.map((item) => <option key={item}>{item}</option>)}</select></label><label>Catalogue<select value={stockFilter} onChange={(event) => setStockFilter(event.target.value)}><option value="all">All products</option><option value="high">High demand</option><option value="low">Low stock</option><option value="out">Out of stock</option></select></label><span>{visible.length} matching products</span></div>
      <div className="pos-grid">{visible.map((product) => {
        const out = product.stock <= 0;
        const low = !out && product.stock < Number(product.lowStockLevel ?? 8);
        return <button key={product.id} className="pos-product" onClick={() => add(product)} disabled={out}><span className="product-monogram">{product.name.slice(0, 2).toUpperCase()}</span><b>{product.name}</b><small>{product.sku || product.id}{[product.colour, product.size].filter(Boolean).length ? ` · ${[product.colour, product.size].filter(Boolean).join(" / ")}` : ""}</small><div><strong>{money.format(product.price)}</strong><span className={out ? "out" : low ? "low" : "healthy"}>{out ? "Out of stock" : low ? `Low stock · ${product.stock} left` : `${product.stock} in stock`}</span></div></button>;
      })}</div>
    </section>
    <aside className={`till-cart ${cartOpen ? "open" : ""}`}><div className="drawer-title"><div><p className="eyebrow">Current basket</p><h2>{cart.reduce((sum, item) => sum + item.quantity, 0)} items · {money.format(total)}</h2></div><button className="pos-cart-toggle" onClick={() => setCartOpen((open) => !open)}>{cartOpen ? "Close" : "Checkout"}</button><button className="text-button" onClick={() => { setCart([]); setOrderReference(""); setOrderChannel("walk-in"); setCustomerName(""); setCustomerPhone(""); setAmountPaid(""); setTransactionVerified(false); }}>Clear</button></div>
      <div className="till-lines">{cart.length ? cart.map((item) => <div className="till-line" key={item.id}><div><b>{item.name}</b><small>{item.sku || item.id} · {[item.colour, item.size].filter(Boolean).join(" / ")} · {money.format(item.price)} each</small></div><div className="stepper"><button aria-label={`Remove one ${item.name}`} onClick={() => change(item.id, -1)}>−</button><span>{item.quantity}</span><button aria-label={`Add one ${item.name}`} onClick={() => change(item.id, 1)} disabled={item.quantity >= item.stock}>+</button></div><strong>{money.format(pricing.lines.find((line) => line.id === item.id)?.lineTotal || 0)}</strong><button className="pos-remove-line" onClick={() => setCart((current) => current.filter((line) => line.id !== item.id))}>Remove</button></div>) : <div className="empty-state"><span className="status-icon">+</span><h3>Your cart is empty</h3><p>Select products to begin a sale.</p></div>}</div>
      <div className="till-checkout">{cartNotice && <div className="notice error-notice pos-cart-notice" role="alert"><span>{cartNotice}</span><button onClick={() => setCartNotice("")}>I reviewed the cart</button></div>}<label>Sales channel<select value={orderChannel} onChange={(event) => setOrderChannel(event.target.value)}><option value="walk-in">Walk-in Sale</option><option value="website">Website Order</option><option value="whatsapp">WhatsApp Order</option><option value="phone">Phone Order</option></select></label><label>Customer / order reference<input placeholder={orderChannel === "walk-in" ? "Optional" : "Order number or WhatsApp reference"} value={orderReference} onChange={(event) => setOrderReference(event.target.value)} /></label><div className="pos-customer-fields"><label>Customer name<input placeholder="Optional for walk-in" value={customerName} onChange={(event) => setCustomerName(event.target.value)} /></label><label>Phone<input type="tel" placeholder="Customer phone" value={customerPhone} onChange={(event) => setCustomerPhone(event.target.value)} /></label></div>
        <div className="till-summary"><div><span>Subtotal</span><strong>{money.format(subtotal)}</strong></div><div><span>Discount</span><strong>−{money.format(discount)}</strong></div><div className="grand-total"><span>Total</span><strong>{money.format(total)}</strong></div><div className="payment-methods">{[["cash", "Cash"], ["mobile-money", "Mobile Money"], ["card", "Card"], ["bank-transfer", "Bank transfer"]].map(([id, label]) => <button key={id} className={paymentMethod === id ? "active" : ""} onClick={() => { setPaymentMethod(id); setTransactionVerified(false); }} disabled={!online && id !== "cash"}>{label}</button>)}</div><label className="amount-paid">Amount paid<input type="number" min="0" step="0.01" placeholder="Enter amount" value={amountPaid} onChange={(event) => setAmountPaid(event.target.value)} /></label>{paymentMethod !== "cash" && <label className="pos-verify"><input type="checkbox" checked={transactionVerified} onChange={(event) => setTransactionVerified(event.target.checked)} /> Transaction verified with provider</label>}{changeDue > 0 && <div className="change-due"><span>Change due</span><strong>{money.format(changeDue)}</strong></div>}<button className="button accent full" onClick={() => setConfirmSale(true)} disabled={!cart.length || !online || !paymentReady || !referenceReady || Boolean(cartNotice) || busy}>Complete Sale</button>{!online && <p className="pos-checkout-warning">Reconnect to save a sale and issue its receipt.</p>}</div>
      </div>
    </aside>
  </main>;
}

